Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -48,19 +48,28 @@ jobs:
      - name: Install dependencies
        run: |
           apt-get update
-          apt-get install -y curl tar docker.io 
+          apt-get install -y curl tar docker.io
 
      - name: Start Selenium manually
        run: |
           docker run -d --name selenium_test \
           --shm-size=2g -p 4444:4444 \
           selenium/standalone-chrome:126.0
+      
+     - name: check Docker-containers
+       if: always()
+       run: docker ps -a    
 
-     - name: Wait for Selenium to be ready
+     - name: Wait for Selenium to start
        run: |
-          echo "Waiting for Selenium to start..."
-          sleep 10
-          curl -v http://localhost:4444/status || true
+        echo "Waiting for Selenium..."
+        for i in {1..10}; do
+        curl -s http://localhost:4444/status && exit 0
+        echo "Selenium not ready yet..."
+        sleep 2
+        done
+        echo "Selenium failed to start"
+        exit 1
           
      - name: Run Selenium Java tests
        run: |
